my_profile/urls.py
from django.urls import include, path
from . import views
from .views import all_event, add_event, delete_all, delete_event
app_name = 'my_profile'

urlpatterns = [
	path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('resume/', views.resume, name='resume'),
    path('connect/', views.connect, name='connect'),
    path('gallery/', views.gallery, name='gallery'),
   

    path('all_event/', views.all_event, name='all_event'),
    path('add_event/', views.add_event, name='add_event'),
    path('delete_all/', views.delete_all, name='delete_all'),
    path('delete_event/<int:pk>', views.delete_event, name='delete_event'),

    
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_profile.urls')),


]

my_profile/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date
from django.utils import timezone
# Create your models here.

class Event(models.Model):
	category = models.CharField(blank=False, max_length=20)
	event_name = models.CharField(blank=False, max_length=30)
	date_time = models.DateTimeField(blank=False, default=timezone.now)
	# start_time = models.TimeField(blank=True, null=True)
	location = models.TextField(blank=True, null=True)
	notes = models.TextField(blank=True, null=True, max_length=150)

	def __str__(self):
		return self.event_name

    # class Meta:
    #     verbose_name = 'Scheduling'
    #     verbose_name_plural = 'Scheduling'

# class Person(models.Model):
# 	email =  models.CharField(max_length=30)

# class Buku(models.Model):
# 	judul =  models.CharField(max_length=30)
# 	author =  models.CharField(max_length=30)

my_profile/forms.py
from django import forms
from django.forms import Form
from django.utils import timezone


CATEGORY_CHOICES = [
    ('Academic','Academic'),
    ('Entertainment','Entertainment'),
    ('Family','Family'),
    ('Friends','Friends'),
    ('Organization','Organization'),
    ('Other','Other')
    ]

class Event_Form(forms.Form):

    pos_attrs = {
        'class': 'form-control',
        
    }
    category = forms.CharField(label='Category', required=True, widget=forms.Select(choices=CATEGORY_CHOICES))
    event_name = forms.CharField(label='Name', required=True, max_length=40, widget=forms.TextInput(attrs=pos_attrs))
    date_time = forms.DateTimeField(
                input_formats=['%d/%m/%Y %H:%M'],
                widget=forms.DateTimeInput(attrs={
                'class': 'form-control datetimepicker-input',
                    'data-target': '#datetimepicker1'
                })
                )
    # start_time = forms.TimeField(label="Time",required=False)
    location = forms.CharField(label="Location", required=False)
    notes = forms.CharField(label="Notes", widget=forms.Textarea(attrs=pos_attrs), required=False, max_length=150)

my_profile/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .forms import Event_Form
from .models import Event
from django.contrib import messages


response = {}

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def resume(request):
    return render(request, 'resume.html')

def connect(request):
    return render(request, 'connect.html')

def gallery(request):
    return render(request, 'gallery.html')

def add_event(request):
  

    if request.method == 'POST':
        
   
        # A POST request: Handle Form Upload
        form = Event_Form(request.POST) # Bind data from request.POST into a PostForm
 
        # If data is valid, proceeds to create a new post and redirect the user
        if form.is_valid():
            messages.success(request, 'Event added succesfully!')

            category = form.cleaned_data['category']
            event_name = form.cleaned_data['event_name']
            date_time = form.cleaned_data['date_time']
          
            location = form.cleaned_data['location']
            notes = form.cleaned_data['notes']
            event = Event.objects.create(category=category, 
                                        event_name=event_name, 
                                        date_time=date_time,
                                       
                                        location=location,
                                        notes=notes)
            # return HttpResponseRedirect(reverse('post_detail',
            #                                     kwargs={'post_id': post.id}))
            return redirect('my_profile:add_event')
    else:

        form = Event_Form()

    return render(request, 'addevent.html', {
        'form': form,
    })

def all_event(request):
    allevents = Event.objects.all()
    context={
    'allevents':allevents
    }
    return render(request, 'allevent.html', context)

def delete_event(request, pk):
    Event.objects.filter(pk=pk).delete()
    allevents = Event.objects.all()
    context = {'allevents':allevents}

    return redirect('my_profile:all_event')
    

def delete_all(request):
    if request.method == "POST":
        Event.objects.all().delete()
        allevents = Event.objects.all()
        context = {'allevents':allevents}
        
        return redirect('my_profile:all_event')
    else:
        return redirect('my_profile:all_event')

my_profile/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<html lang="en">
	<head>
		 
		<title>About me</title>

	</head>

	<body style="background-color: #E1B0A2;">




    <!--Section 2: About me-->
    <section id="about">

    	
    	
    	<div class="container-fluid ">

	   		<div class="row pagePadding" style="height: 200px;  ">

	   			
	   		
				<h3 class="pageTitle" style="color:#FFFBFB; "> about me</h3>
				
				
		
			</div>
			<!-- <img class="svg img-fluid" src="flower.svg" style="right: 0%"> -->

			<div class="row pagePadding" style="height: 400px;">

				<h4 class="text">Currently, I am in my third semester  majoring 
					computer science in Universitas Indonesia. 
					Being a web designer is one of 
					my future goal since 10th grade, 
					but now I also interested in data science.
					I still finding my passion and what kind of job 
					i really want after I achieve my bachelor degree. 

					<br><br>Beside academic interest, 
					I have hobbies that have nothing to do with my studies, 
					that is taking photos and sometimes read fiction book.
				</h4>
						
			


				<!-- <div class="col-sm-4" style="color: #FFFBFB;">
					
				</div> -->
				
			</div>
		</div>
		

		

	
		
	</section>
	
	</body>

</html>

{% endblock %}

my_profile/templates/addevent.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<html lang="en">
  <head>

    <title>Add Event</title>



  </head>

  <body style="background-color: #BCCEB8;">
    <div class="container" style="padding-top: 100px;">
  
        <h2 class="pageTitle" style=" text-align: center">add new event</h2>

        
        {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}

        <form action="{% url 'my_profile:add_event' %}" method="POST">
          {% csrf_token %}

          <div class="form-group">

              {{form.category.label}} <br>
              {{form.category}} <br>

              {{form.event_name.label}} <br>
              {{form.event_name}}

              {{form.date_time.label}} <br>
              <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                
                {{ form.date_time }} <br>
                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                  <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
              </div>
              {{form.location.label}} <br>
              {{ form.location }} <br>

              {{form.notes.label}} <br>
              {{ form.notes }}

              <!-- <div class="input-group date" id="datetimepicker1" data-target-input="nearest"> 
              <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
              </div> -->
          </div>
          <button type='submit' class="btn btn-secondary">Submit</button>

          <a href="{% url 'my_profile:all_event' %}" class="btn btn-secondary">Back to My Events</a>

        </form>
   
    </div> 

    <script>
      $(function () {
        $("#datetimepicker1").datetimepicker({
          format: 'DD/MM/YYYY HH:mm',
        });
      });
    </script>
    
  </body>
</html>
{% endblock %}

my_profile/templates/allevent.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<html lang="en">
	<head>
		
		<title>My Events</title>

		

	</head>

	<body style="background-color: #EDCFC4;">

		<div class="container-fluid" style="padding-top: 20px;">

			<h2 class="pageTitle" style=" text-align: center">my events</h2>

		</div>

		<div class="container-fluid" style="padding-top: 40px;">
			
			<table class="table">
			    <thead>
			    	<th>Category</th>
			        <th>Name</th>
			        <th>Date/Time</th>
			        <th>Location</th>
			        <th>Notes</th>
			        <th></th>
			    </thead>
			    <tbody>
			        
			        {% for event in allevents %}
			  
			        <tr class="success">
			        	<td> {{event.category}} </td>
			            <td> {{event.event_name}} </td>
			            <td> {{event.date_time}} </td>
			            <td> {{event.location}} </td>
			            <td> {{event.notes}} </td>

			            <td><a href="{% url 'my_profile:delete_event' pk=event.pk %}" ><button type="button" class="btn btn-icon btn-danger">Delete</button></a></td>

			        </tr>             
			        {% endfor %}
			    </tbody>
			</table>

			<a href="{% url 'my_profile:add_event' %}" class="btn btn-secondary" role="button">Add new event</a>

			<form method="POST" action="{% url 'my_profile:delete_all' %}">
	            {% csrf_token %}
	            <button type="submit" class="btn btn-icon btn-danger">Delete All</button>
	        </form>
				
			
		</div>
	


	
	
	</body>

</html>
{% endblock%}

my_profile/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8"> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 

    <!--Links for styles and font-->

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/story3.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/tempusdominus-bootstrap-4.min.css' %}">

      <!-- <link rel="stylesheet" href="{%static 'css/style.css' %}">   -->
    <link href="https://fonts.googleapis.com/css?family=Arizonia|Cardo&display=swap" rel="stylesheet"> 
    
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>
    
    <!-- Tempus Dominus Bootstrap 4 -->
    <script src="{% static 'js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
   

  </head>
  
  <body>
    {% include "header.html" %}
    {% block content %}{% endblock %}

  </body>
</html>

my_profile/templates/connect.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<html lang="en">
	<head>
		
		<title>Let's Connect!</title>

		
	</head>

	<body style="background-color: #7A716F;">

		
	<!--Section 4: Connect-->

	<section id="connect">

		
		<div class="container-fluid">

			<div class="row pagePadding" style="padding-top: 160px; padding-bottom: 250px; ">
				
	   				
				<div class="col-sm-6" style="position: relative; height: 200px; ">
					
					<h3 class="pageTitle" >let's connect!</h3>
					
					
				</div>

				<div class="col-sm-6">
					
					<p><a href="mailto:yasminadelia11@gmail.com?subject=Hello%20Yasmin" target="_blank">
						<img class="img-fluid" alt="icon" style="vertical-align:middle" src="{% static 'images/mail.png' %}" > 
						<span style="">yasminadelia11@gmail.com</span></a></p>
					

					<p><a href="https://id.linkedin.com/in/yasmin-adelia-92b641177" target="_blank">
						<img  class="img-fluid" alt="icon" style="vertical-align:middle" src="{% static 'images/linkedin.png' %}">
						<span style="">Yasmin Adelia</span></a></p>

				
					<p><a href="https://www.instagram.com/yasminadelia/" target="_blank">
						<img class="img-fluid" alt="icon" style="vertical-align:middle" src="{% static 'images/ig.png' %}">
						<span style="">yasminadelia</span></a></p>
						
				</div>
			</div>
		</div>
		
			
	</section>
	
	</body>

</html>

{% endblock %}

my_profile/templates/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<html lang="en">
	<head>
		
		<title>Gallery</title>


		<style>
		  /* Make the image fully responsive */
	  	.carousel-inner img {
	    	width: 50%;
	      	height: 50%;
		}
  		</style>
	</head>

	<body style="background-color: #EDCFC4;">

	<!-- Section 5: Gallery -->

	<section id="gallery">

		<div class="container-fluid" >
							
					
				<h2 class="pageTitle" style=" text-align: center">gallery</h2>
					
				
			
				<div  class="row" >
					
					<div id="carTarget" class="carousel slide" data-ride="carousel">

					  <!-- Indicators -->
					  <ul class="carousel-indicators">
					    <li data-target="#carTarget" data-slide-to="0" class="active"></li>
					    <li data-target="#carTarget" data-slide-to="1"></li>
					    <li data-target="#carTarget" data-slide-to="2"></li>
					    <li data-target="#carTarget" data-slide-to="3"></li>
					    <li data-target="#carTarget" data-slide-to="4"></li>
					    <li data-target="#carTarget" data-slide-to="5"></li>
					  </ul>

					  <!-- The slideshow -->
					  <div class="carousel-inner">
					    <div class="carousel-item active">
					      <center><img src="{% static 'images/1.jpg' %}" class="imageGallery" alt="Medan"></center>
					    </div>
					    <div class="carousel-item">
					       <center><img src="{% static 'images/9.jpg' %}" class="imageGallery" alt="Jakarta"></center>
					    </div>
					    <div class="carousel-item">
					       <center><img src="{% static 'images/7.jpg' %}" class="imageGallery"  alt="Jakarta"></center>
					    </div>
					    <div class="carousel-item">
					       <center><img src="{% static 'images/5.jpg' %}" class="imageGallery" alt="Jakarta"></center>
					    </div>
					    <div class="carousel-item">
					       <center><img src="{% static 'images/6.jpg' %}" class="imageGallery" alt="Jakarta"></center>
					    </div>
					    <div class="carousel-item">
					       <center><img src="{% static 'images/8.jpg' %}" class="imageGallery" alt="Jakarta"></center>
					    </div>
					  </div>

					  <!-- Left and right controls -->
					  <a class="carousel-control-prev" href="#carTarget" data-slide="prev">
					    <span class="carousel-control-prev-icon"></span>
					  </a>
					  <a class="carousel-control-next" href="#carTarget" data-slide="next">
					    <span class="carousel-control-next-icon"></span>
					  </a>
					</div>
					
				</div>
			
		</div>
	
		
	</section>

	
	
	</body>

</html>

{% endblock %}

my_profile/templates/header.html
{% load static %}
<!-- navigation bar -->

<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <a class="navbar-brand" href=""><img alt=logo src="{% static 'images/logo.svg' %}"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'my_profile:home' %}"><img src="{% static 'images/home.svg' %}" width="80px"> <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'my_profile:about' %}"><img src="{% static 'images/about.svg' %}" width="80px"></a>
      <a class="nav-item nav-link" href="{% url 'my_profile:resume' %}"><img src="{% static 'images/resume.svg' %}" width="80px"></a>
      <a class="nav-item nav-link" href="{% url 'my_profile:all_event' %}"><img src="{% static 'images/event.svg' %}" width="80px"></a>
      <a class="nav-item nav-link" href="{% url 'my_profile:connect' %}"><img src="{% static 'images/connect.svg' %}" width="80px"></a>
      <a class="nav-item nav-link" href="{% url 'my_profile:gallery' %}"><img src="{% static 'images/gallery.svg' %}" width="80px"></a>

      
      
    </div>
  </div>
</nav>

my_profile/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


	<head>
		 
		<title>Yasmin's profile</title>

		<!--Links for styles and font-->

	</head>

	<body style="background-color: #EDCFC4;">
	
	<section id="home">
    	<img class="img-fluid" src="{% static 'images/daun1.svg' %}">
    
   		<div class="container-fluid" style="position:absolute; top:30%">
   			<div class="row">
   				
				<div class="col-sm-12" style="text-align: center;">
					<h4> Hello I'm</h4>
				</div>
							
			</div>

			<div class="row" >
				
				<div class="col-sm-12" style="text-align: center;">
					<h1 class="pageTitle" style="font-family: Arizonia, cursive; color: #000000; text-shadow: 10px 20px 15px rgba(0, 0, 0, 0.25);">Yasmin</h1>
				</div>
			</div>
				

			<div class="row">
   				
				<div class="col-sm-12" style="text-align: center;">
					<h4>I'm a computer <br>science student.</h4>
				</div>

			</div>
		</div>
			
	
	</section>
    

   </body>



{% endblock %}

my_profile/templates/resume.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<html lang="en">
	<head>
		
		<title>My Resume</title>

		
	</head>

	<body style="background-color: #BCCEB8;">
	

	<!--Section 3: Resume-->
	<section id="resume">

		<img class="svg img-fluid" src="{% static 'images/daun2.svg' %}" style="left: 0px" >

		<div class="container-fluid" >

	   			<div class="row" >
	   				

					<div class="col-sm-12">
						<h3 class="pageTitle" style="text-align: center;">resume </h3>
					</div>
								
				</div>
			
			
				<div class="row pagePadding">

					<div class="col-sm-4" style="height: 300px;">
						
							<!-- style="float: center;" -->
							<img alt="Profile photo" class="photo img-fluid" src="https://live.staticflickr.com/65535/48698361713_e260db12c4_m.jpg">
											
					</div>

					<div class="col-sm-4" style="height: 500px;">
						
						
						<strong>Name</strong><br>Yasmin Adelia Puti Chaidir
						<br><br>
						<strong>Born</strong><br>11 November 2000
						<br><br>
						<strong>Education</strong>
						<ul>
						  <li>Universitas Indonesia   (2018-now)</li>
						  <li>SMAN 26 Jakarta         (2015-2018)</li>
						  <li>SMPI Al-Azhar 19        (2012-2015)</li>
						</ul> 
						
					</div>

					

					<div class="col-sm-4" style="height: 300px;">
						<strong>Skill</strong>
						<ul>
							<li>Java</li>
							<li>Python</li>
							<li>Power BI</li>
							<li>Photography</li>
						</ul>
						
						<strong>Experience</strong>
						<ul>
						  <li>FUKI 2019 : Staff of Muslimah Center</li>
						  <li>Wisgen 2019 : Staff of Documentation</li>
						  <li>She Loves Data: Participant of Data Visualization Workshop</li>
						  <li>CGT 2019 : Staff of Documentation</li>
						</ul> 

							
					</div>
				</div>
		</div>
		
		
			
		
	</section>

	
	</body>

</html>

{% endblock %}